name: Test getUserTVLByBlock method

on:
  pull_request:
    paths:
      - '**/'  # Listen for changes in any directory

jobs:
  test-adapters:
    runs-on: ubuntu-latest
    env:
      FOLDER_NAME: ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Get changed files in the adapters folder
      - name: Get changed files in adapters folder
        id: changed_files_adapters
        uses: Ana06/get-changed-files@v2.1.0
        with:
          filter: 'adapters/**/*'

      # Extract unique folder names from changed files
      - name: Extract changed folders
        id: extract_folders
        run: |
          # Extract unique folder names from changed files
          changed_folders=$(echo "${{ steps.changed_files_adapters.outputs.files }}" | awk -F/ '{print $2}' | sort -u)
          echo "::set-output name=changed_folders::$changed_folders"

      - name: Print changed folders
        run: |
          echo "Changed folders: ${{ steps.extract_folders.outputs.changed_folders }}"

      # Loop through changed folders and run commands
      - name: Run commands in each folder
        run: |
          for folder in ${{ steps.extract_folders.outputs.changed_folders }}; do
            cd adapters/$folder
            npm install
            npm run compile
            cd ../../
            npm install
            npm run start $folder
          done
