name: Test getUserTVLByBlock method

on:
  pull_request:
    paths:
      - '**/'  # Listen for changes in any directory

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      FOLDER_NAME: ""
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Get changed files
        id: changed_files
        uses: jitterbit/get-changed-files@v1
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract folder names
        run: |
          added="${{ steps.changed_files.outputs.added }}"
          edited="${{ steps.changed_files.outputs.edited }}"
          # Combine added and edited folders
          all_folders=$(echo "$added $edited" | awk -F/ '{print $2}' | sort -u)
          echo "FOLDER_NAME=$all_folders" >> $GITHUB_ENV
      - name: Print folder name
        run: |
          echo "Folder name(s): $FOLDER_NAME"
      - name: Checkout PR
        uses: actions/checkout@v2.1.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run command from protocol folder
        run: |
          cd adapters 
          cd $FOLDER_NAME
          npm install
          npm run compile
          cd ..
          npm install
          npm run start $FOLDER_NAME
